- name: Create /etc/rancher/rke2 directory
  ansible.builtin.file:
    path: /etc/rancher/rke2
    state: directory
    mode: '0700'

- name: Create rke2 config file
  ansible.builtin.template:
    src: config/master-init.yaml.j2
    dest: /etc/rancher/rke2/config.yaml
    mode: '0600'

- name: Create /var/lib/rancher/rke2/server/manifests
  ansible.builtin.file:
    path: /var/lib/rancher/rke2/server/manifests
    state: directory
    mode: '0700'

- name: Create /var/lib/rancher/rke2/agent/pod-manifests
  ansible.builtin.file:
    path: /var/lib/rancher/rke2/agent/pod-manifests
    state: directory
    mode: '0700'

- name: Create cilium manifest
  ansible.builtin.template:
    src: manifests/cilium.yaml.j2
    dest: /var/lib/rancher/rke2/server/manifests/cilium.yaml
    mode: '0600'

- name: Create kube-vip manifest
  ansible.builtin.template:
    src: pod-manifests/kube-vip.yaml.j2
    dest: /var/lib/rancher/rke2/agent/pod-manifests/kube-vip.yaml
    mode: '0600'

- name: Install RKE2 server
  ansible.builtin.shell: |
    curl -sfL https://get.rke2.io | sh -

- name: Enable and start RKE2 server
  ansible.builtin.service:
    name: rke2-server
    state: started
    enabled: true

- name: Wait for VIP to be active
  ansible.builtin.wait_for:
    host: "{{ rke2_vip }}"
    port: 9345
    timeout: 300
