- name: Prepare all nodes
  hosts: all
  become: true
  gather_facts: false
  any_errors_fatal: true
  tags:
    - preflight
    - host_prep
    - bootstrap
    - always
  roles:
    - rke2-common

- name: Initialize first master node
  hosts: kube-masters[0]
  become: true
  gather_facts: false
  any_errors_fatal: true
  tags:
    - master_init
    - control_plane
    - bootstrap
  roles:
    - role: rke2-master
      tasks_from: init

- name: Gather bootstrap artifacts from first master
  hosts: kube-masters[0]
  become: true
  gather_facts: false
  any_errors_fatal: true
  tags:
    - bootstrap_artifacts
    - master_join
    - workers
    - control_plane
    - bootstrap
  roles:
    - bootstrap-artifacts

- name: Join additional master nodes
  hosts: kube-masters[1:]
  become: true
  gather_facts: false
  any_errors_fatal: true
  serial: 1
  tags:
    - master_join
    - control_plane
    - bootstrap
  roles:
    - rke2-master

- name: Join worker nodes
  hosts: kube-workers
  become: true
  gather_facts: false
  any_errors_fatal: true
  tags:
    - workers
    - bootstrap
  roles:
    - rke2-worker

- name: Enroll cluster in parent ArgoCD
  hosts: localhost
  connection: local
  gather_facts: false
  any_errors_fatal: true
  tags:
    - argocd_enroll
  roles:
    - role: argocd
      tasks_from: enroll
